name: Template Lint
on:
  push:
    paths:
      - '.github/**'
  pull_request:
    paths:
      - '.github/**'

jobs:
  lint-templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
          VALIDATE_JSON: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_WORKING_DIRECTORY: ./
